{
  "name": "Day after dataflow",
  "description": "Demo of a dataflow for Day after Dashboard in a Day event.",
  "version": "1.0",
  "culture": "en-US",
  "modifiedTime": "2022-04-13T18:07:52.4701941+00:00",
  "pbi:mashup": {
    "fastCombine": false,
    "allowNativeQueries": false,
    "queriesMetadata": {
      "DimProduct_raw": {
        "queryId": "b2a9c1da-3f2f-49c8-8d59-622dee438105",
        "queryName": "DimProduct_raw",
        "loadEnabled": true
      },
      "DimProductCategory_raw": {
        "queryId": "415d50a7-90b2-45f7-acfb-195f3782dcd8",
        "queryName": "DimProductCategory_raw",
        "loadEnabled": true
      },
      "DimProductSubcategory_raw": {
        "queryId": "a3c281f5-6af9-47fa-913d-77694e2d098c",
        "queryName": "DimProductSubcategory_raw",
        "loadEnabled": true
      },
      "DimCustomer_raw": {
        "queryId": "b8782f36-de41-4e0e-9c85-853fbfca4252",
        "queryName": "DimCustomer_raw",
        "loadEnabled": true
      },
      "DimGeography_raw": {
        "queryId": "cc87ce39-7471-4ffa-abc8-6c5e4ef0e8f7",
        "queryName": "DimGeography_raw",
        "loadEnabled": true
      },
      "DimDate": {
        "queryId": "37f72102-aa25-4005-b517-080c52baecd0",
        "queryName": "DimDate",
        "loadEnabled": true
      },
      "DimEmployee": {
        "queryId": "c2a07242-3c8f-4c3d-bb24-f3934eb7f4f1",
        "queryName": "DimEmployee",
        "loadEnabled": true
      },
      "DimStore": {
        "queryId": "3665add6-e018-4c43-a607-5e2023904cc8",
        "queryName": "DimStore",
        "loadEnabled": true
      },
      "fxGetFile": {
        "queryId": "620769f7-b1ac-4a7c-8998-1d0d38736fe1",
        "queryName": "fxGetFile"
      },
      "fxCreateKey": {
        "queryId": "a0203672-4b21-42b0-8746-0d6bcf495812",
        "queryName": "fxCreateKey"
      }
    },
    "document": "section Section1;\r\nshared DimProduct_raw = let\n    Source = fxGetFile(\"DimProduct.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"LoadDate\",\n                    type datetime\n                },\n                {\n                    \"UpdateDate\",\n                    type datetime\n                },\n                {\n                    \"AvailableForSaleDate\",\n                    type datetime\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimProductCategory_raw = let\n    Source = fxGetFile(\"DimProductCategory.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"ProductCategoryKey\",\n                    Int64.Type\n                },\n                {\n                    \"ProductCategoryLabel\",\n                    Int64.Type\n                },\n                {\n                    \"ProductCategoryName\",\n                    type text\n                },\n                {\n                    \"ProductCategoryDescription\",\n                    type text\n                },\n                {\n                    \"ETLLoadID\",\n                    Int64.Type\n                },\n                {\n                    \"LoadDate\",\n                    type datetime\n                },\n                {\n                    \"UpdateDate\",\n                    type datetime\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimProductSubcategory_raw = let\n    Source = fxGetFile(\"DimProductSubcategory.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"ProductSubcategoryKey\",\n                    Int64.Type\n                },\n                {\n                    \"ProductSubcategoryLabel\",\n                    Int64.Type\n                },\n                {\n                    \"ProductSubcategoryName\",\n                    type text\n                },\n                {\n                    \"ProductSubcategoryDescription\",\n                    type text\n                },\n                {\n                    \"ProductCategoryKey\",\n                    Int64.Type\n                },\n                {\n                    \"ETLLoadID\",\n                    Int64.Type\n                },\n                {\n                    \"LoadDate\",\n                    type datetime\n                },\n                {\n                    \"UpdateDate\",\n                    type datetime\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimCustomer_raw = let\n    Source = fxGetFile(\"DimCustomer.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"CustomerKey\",\n                    Int64.Type\n                },\n                {\n                    \"GeographyKey\",\n                    Int64.Type\n                },\n                {\n                    \"CustomerLabel\",\n                    type text\n                },\n                {\n                    \"Title\",\n                    type text\n                },\n                {\n                    \"FirstName\",\n                    type text\n                },\n                {\n                    \"MiddleName\",\n                    type text\n                },\n                {\n                    \"LastName\",\n                    type text\n                },\n                {\n                    \"NameStyle\",\n                    Int64.Type\n                },\n                {\n                    \"BirthDate\",\n                    type date\n                },\n                {\n                    \"MaritalStatus\",\n                    type text\n                },\n                {\n                    \"Suffix\",\n                    type text\n                },\n                {\n                    \"Gender\",\n                    type text\n                },\n                {\n                    \"EmailAddress\",\n                    type text\n                },\n                {\n                    \"YearlyIncome\",\n                    Int64.Type\n                },\n                {\n                    \"TotalChildren\",\n                    Int64.Type\n                },\n                {\n                    \"NumberChildrenAtHome\",\n                    Int64.Type\n                },\n                {\n                    \"Education\",\n                    type text\n                },\n                {\n                    \"Occupation\",\n                    type text\n                },\n                {\n                    \"HouseOwnerFlag\",\n                    Int64.Type\n                },\n                {\n                    \"NumberCarsOwned\",\n                    Int64.Type\n                },\n                {\n                    \"AddressLine1\",\n                    type text\n                },\n                {\n                    \"AddressLine2\",\n                    type text\n                },\n                {\n                    \"Phone\",\n                    type text\n                },\n                {\n                    \"DateFirstPurchase\",\n                    type date\n                },\n                {\n                    \"CustomerType\",\n                    type text\n                },\n                {\n                    \"CompanyName\",\n                    type text\n                },\n                {\n                    \"ETLLoadID\",\n                    Int64.Type\n                },\n                {\n                    \"LoadDate\",\n                    type datetime\n                },\n                {\n                    \"UpdateDate\",\n                    type datetime\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimGeography_raw = let\n    Source = fxGetFile(\"DimGeography.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"GeographyKey\",\n                    Int64.Type\n                },\n                {\n                    \"GeographyType\",\n                    type text\n                },\n                {\n                    \"ContinentName\",\n                    type text\n                },\n                {\n                    \"CityName\",\n                    type text\n                },\n                {\n                    \"StateProvinceName\",\n                    type text\n                },\n                {\n                    \"RegionCountryName\",\n                    type text\n                },\n                {\n                    \"Geometry\",\n                    type text\n                },\n                {\n                    \"ETLLoadID\",\n                    Int64.Type\n                },\n                {\n                    \"LoadDate\",\n                    type datetime\n                },\n                {\n                    \"UpdateDate\",\n                    type datetime\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimDate = let\n    Source = fxGetFile(\"DimDate.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"Datekey\",\n                    type datetime\n                },\n                {\n                    \"FullDateLabel\",\n                    type date\n                },\n                {\n                    \"DateDescription\",\n                    type date\n                },\n                {\n                    \"CalendarYear\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarYearLabel\",\n                    type text\n                },\n                {\n                    \"CalendarHalfYear\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarHalfYearLabel\",\n                    type text\n                },\n                {\n                    \"CalendarQuarter\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarQuarterLabel\",\n                    type text\n                },\n                {\n                    \"CalendarMonth\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarMonthLabel\",\n                    type text\n                },\n                {\n                    \"CalendarWeek\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarWeekLabel\",\n                    type text\n                },\n                {\n                    \"CalendarDayOfWeek\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarDayOfWeekLabel\",\n                    type text\n                },\n                {\n                    \"FiscalYear\",\n                    Int64.Type\n                },\n                {\n                    \"FiscalYearLabel\",\n                    type text\n                },\n                {\n                    \"FiscalHalfYear\",\n                    Int64.Type\n                },\n                {\n                    \"FiscalHalfYearLabel\",\n                    type text\n                },\n                {\n                    \"FiscalQuarter\",\n                    Int64.Type\n                },\n                {\n                    \"FiscalQuarterLabel\",\n                    type text\n                },\n                {\n                    \"FiscalMonth\",\n                    Int64.Type\n                },\n                {\n                    \"FiscalMonthLabel\",\n                    type text\n                },\n                {\n                    \"IsWorkDay\",\n                    type text\n                },\n                {\n                    \"IsHoliday\",\n                    Int64.Type\n                },\n                {\n                    \"HolidayName\",\n                    type text\n                },\n                {\n                    \"EuropeSeason\",\n                    type text\n                },\n                {\n                    \"NorthAmericaSeason\",\n                    type text\n                },\n                {\n                    \"AsiaSeason\",\n                    type text\n                }\n            }\n        ),\n    #\"Calculated date\" =\n        Table.TransformColumns(\n            #\"Changed column type\",\n            {\n                {\n                    \"Datekey\",\n                    each DateTime.Date(_),\n                    type nullable date\n                }\n            }\n        )\nin\n    #\"Calculated date\";\r\nshared DimEmployee = let\n    Source = fxGetFile(\"DimEmployee.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"EmployeeKey\",\n                    Int64.Type\n                },\n                {\n                    \"ParentEmployeeKey\",\n                    Int64.Type\n                },\n                {\n                    \"FirstName\",\n                    type text\n                },\n                {\n                    \"LastName\",\n                    type text\n                },\n                {\n                    \"MiddleName\",\n                    type text\n                },\n                {\n                    \"Title\",\n                    type text\n                },\n                {\n                    \"HireDate\",\n                    type date\n                },\n                {\n                    \"BirthDate\",\n                    type date\n                },\n                {\n                    \"EmailAddress\",\n                    type text\n                },\n                {\n                    \"Phone\",\n                    type text\n                },\n                {\n                    \"MaritalStatus\",\n                    type text\n                },\n                {\n                    \"EmergencyContactName\",\n                    type text\n                },\n                {\n                    \"EmergencyContactPhone\",\n                    type text\n                },\n                {\n                    \"SalariedFlag\",\n                    Int64.Type\n                },\n                {\n                    \"Gender\",\n                    type text\n                },\n                {\n                    \"PayFrequency\",\n                    Int64.Type\n                },\n                {\n                    \"BaseRate\",\n                    type number\n                },\n                {\n                    \"VacationHours\",\n                    Int64.Type\n                },\n                {\n                    \"CurrentFlag\",\n                    Int64.Type\n                },\n                {\n                    \"SalesPersonFlag\",\n                    Int64.Type\n                },\n                {\n                    \"DepartmentName\",\n                    type text\n                },\n                {\n                    \"StartDate\",\n                    type date\n                },\n                {\n                    \"EndDate\",\n                    type date\n                },\n                {\n                    \"Status\",\n                    type text\n                },\n                {\n                    \"ETLLoadID\",\n                    Int64.Type\n                },\n                {\n                    \"LoadDate\",\n                    type datetime\n                },\n                {\n                    \"UpdateDate\",\n                    type datetime\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimStore = let\n    Source = fxGetFile(\"DimStore.csv\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"StoreKey\", Int64.Type}, {\"GeographyKey\", Int64.Type}, {\"StoreManager\", Int64.Type}, {\"StoreType\", type text}, {\"StoreName\", type text}, {\"StoreDescription\", type text}, {\"Status\", type text}, {\"OpenDate\", type datetime}, {\"CloseDate\", type datetime}, {\"EntityKey\", Int64.Type}, {\"ZipCode\", Int64.Type}, {\"ZipCodeExtension\", Int64.Type}, {\"StorePhone\", type text}, {\"StoreFax\", type text}, {\"AddressLine1\", type text}, {\"AddressLine2\", type text}, {\"CloseReason\", type text}, {\"EmployeeCount\", Int64.Type}, {\"SellingAreaSize\", Int64.Type}, {\"LastRemodelDate\", type datetime}, {\"GeoLocation\", type text}, {\"Geometry\", type text}, {\"ETLLoadID\", Int64.Type}, {\"LoadDate\", type datetime}, {\"UpdateDate\", type datetime}})\nin\n    #\"Changed column type\";\r\nshared fxGetFile = let\n    fxGetFile =\n        (#\"File Name\" as text) =>\n            let\n                webAddress = \"https://raw.githubusercontent.com/microsoft/pbiworkshops/main/Day%20After%20Dashboard%20in%20a%20Day/Source_Files\",\n                Source =\n                    if\n                        Text.AfterDelimiter(#\"File Name\", \".\")\n                        = \"csv\"\n                    then\n                        Table.PromoteHeaders(\n                            Csv.Document(\n                                Web.Contents(\n                                    webAddress,\n                                    [\n                                        RelativePath = #\"File Name\",\n                                        ManualStatusHandling = {\n                                            404\n                                        }\n                                    ]\n                                ),\n                                [\n                                    Delimiter = \"|\",\n                                    Encoding = 65001,\n                                    QuoteStyle = QuoteStyle.None\n                                ]\n                            )\n                        )\n                    else\n                        Parquet.Document(\n                            Binary.Buffer(\n                                Web.Contents(\n                                    webAddress,\n                                    [\n                                        RelativePath = #\"File Name\",\n                                        ManualStatusHandling = {\n                                            404\n                                        }\n                                    ]\n                                )\n                            ),\n                            [\n                                Compression = Compression.Snappy,\n                                LegacyColumnNameEncoding = false,\n                                MaxDepth = null\n                            ]\n                        )\n            in\n                Source,\n    Documentation_Meta = [\n        Documentation.Name = \"Day After Dashboard in a Day - Sample data\",\n        Documentation.Description = \"Obtains the pipe delimited csv files from the GitHub repository for Day After Dashboard in a Day. Short link: https://aka.ms/pbiworkshops\"\n    ],\n    #\"Add Documentation\" =\n        Value.ReplaceType(\n            fxGetFile,\n            Value.ReplaceMetadata(\n                Value.Type(fxGetFile),\n                Documentation_Meta\n            )\n        )\nin\n    #\"Add Documentation\";\r\nshared fxCreateKey = let\r\n  CreateKey = (#\"Date time value\" as datetime) as number =>\n            let\n                Source =\n                    DateTime.ToText(\n                        #\"Date time value\",\n                        \"yyyyMMdd\"\n                    ),\n                #\"Convert to number\" = Number.From(Source)\n            in\n                #\"Convert to number\",\r\n  Documentation = [\n        Documentation.Name = \"Create an integer surrogate key\",\n        Documentation.Description = \"Converts a datetime value to an integer in the format of yyyyMMdd.\"\n    ],\r\n  Output = Value.ReplaceType(CreateKey, Value.ReplaceMetadata(Value.Type(CreateKey), Documentation))\r\nin\r\n  Output;\r\n"
  },
  "annotations": [{ "name": "pbi:QueryGroups", "value": "[]" }],
  "entities": [
    {
      "$type": "LocalEntity",
      "name": "DimProduct_raw",
      "description": "Description when connecting.",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimProduct_raw.csv"
      },
      "attributes": [
        { "name": "ProductKey", "dataType": "string" },
        { "name": "ProductLabel", "dataType": "string" },
        { "name": "ProductName", "dataType": "string" },
        { "name": "ProductDescription", "dataType": "string" },
        { "name": "ProductSubcategoryKey", "dataType": "string" },
        { "name": "Manufacturer", "dataType": "string" },
        { "name": "BrandName", "dataType": "string" },
        { "name": "ClassID", "dataType": "string" },
        { "name": "ClassName", "dataType": "string" },
        { "name": "StyleID", "dataType": "string" },
        { "name": "StyleName", "dataType": "string" },
        { "name": "ColorID", "dataType": "string" },
        { "name": "ColorName", "dataType": "string" },
        { "name": "Size", "dataType": "string" },
        { "name": "SizeRange", "dataType": "string" },
        { "name": "SizeUnitMeasureID", "dataType": "string" },
        { "name": "Weight", "dataType": "string" },
        { "name": "WeightUnitMeasureID", "dataType": "string" },
        { "name": "UnitOfMeasureID", "dataType": "string" },
        { "name": "UnitOfMeasureName", "dataType": "string" },
        { "name": "StockTypeID", "dataType": "string" },
        { "name": "StockTypeName", "dataType": "string" },
        { "name": "UnitCost", "dataType": "string" },
        { "name": "UnitPrice", "dataType": "string" },
        { "name": "AvailableForSaleDate", "dataType": "dateTime" },
        { "name": "StopSaleDate", "dataType": "string" },
        { "name": "Status", "dataType": "string" },
        { "name": "ImageURL", "dataType": "string" },
        { "name": "ProductURL", "dataType": "string" },
        { "name": "ETLLoadID", "dataType": "string" },
        { "name": "LoadDate", "dataType": "dateTime" },
        { "name": "UpdateDate", "dataType": "dateTime" }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "DimProductCategory_raw",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimProductCategory_raw.csv"
      },
      "attributes": [
        { "name": "ProductCategoryKey", "dataType": "int64" },
        { "name": "ProductCategoryLabel", "dataType": "int64" },
        { "name": "ProductCategoryName", "dataType": "string" },
        { "name": "ProductCategoryDescription", "dataType": "string" },
        { "name": "ETLLoadID", "dataType": "int64" },
        { "name": "LoadDate", "dataType": "dateTime" },
        { "name": "UpdateDate", "dataType": "dateTime" }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "DimProductSubcategory_raw",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimProductSubcategory_raw.csv"
      },
      "attributes": [
        { "name": "ProductSubcategoryKey", "dataType": "int64" },
        { "name": "ProductSubcategoryLabel", "dataType": "int64" },
        { "name": "ProductSubcategoryName", "dataType": "string" },
        { "name": "ProductSubcategoryDescription", "dataType": "string" },
        { "name": "ProductCategoryKey", "dataType": "int64" },
        { "name": "ETLLoadID", "dataType": "int64" },
        { "name": "LoadDate", "dataType": "dateTime" },
        { "name": "UpdateDate", "dataType": "dateTime" }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "DimCustomer_raw",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimCustomer_raw.csv"
      },
      "attributes": [
        { "name": "CustomerKey", "dataType": "int64" },
        { "name": "GeographyKey", "dataType": "int64" },
        { "name": "CustomerLabel", "dataType": "string" },
        { "name": "Title", "dataType": "string" },
        { "name": "FirstName", "dataType": "string" },
        { "name": "MiddleName", "dataType": "string" },
        { "name": "LastName", "dataType": "string" },
        { "name": "NameStyle", "dataType": "int64" },
        { "name": "BirthDate", "dataType": "date" },
        { "name": "MaritalStatus", "dataType": "string" },
        { "name": "Suffix", "dataType": "string" },
        { "name": "Gender", "dataType": "string" },
        { "name": "EmailAddress", "dataType": "string" },
        { "name": "YearlyIncome", "dataType": "int64" },
        { "name": "TotalChildren", "dataType": "int64" },
        { "name": "NumberChildrenAtHome", "dataType": "int64" },
        { "name": "Education", "dataType": "string" },
        { "name": "Occupation", "dataType": "string" },
        { "name": "HouseOwnerFlag", "dataType": "int64" },
        { "name": "NumberCarsOwned", "dataType": "int64" },
        { "name": "AddressLine1", "dataType": "string" },
        { "name": "AddressLine2", "dataType": "string" },
        { "name": "Phone", "dataType": "string" },
        { "name": "DateFirstPurchase", "dataType": "date" },
        { "name": "CustomerType", "dataType": "string" },
        { "name": "CompanyName", "dataType": "string" },
        { "name": "ETLLoadID", "dataType": "int64" },
        { "name": "LoadDate", "dataType": "dateTime" },
        { "name": "UpdateDate", "dataType": "dateTime" }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "DimGeography_raw",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimGeography_raw.csv"
      },
      "attributes": [
        { "name": "GeographyKey", "dataType": "int64" },
        { "name": "GeographyType", "dataType": "string" },
        { "name": "ContinentName", "dataType": "string" },
        { "name": "CityName", "dataType": "string" },
        { "name": "StateProvinceName", "dataType": "string" },
        { "name": "RegionCountryName", "dataType": "string" },
        { "name": "Geometry", "dataType": "string" },
        { "name": "ETLLoadID", "dataType": "int64" },
        { "name": "LoadDate", "dataType": "dateTime" },
        { "name": "UpdateDate", "dataType": "dateTime" }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "DimDate",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimDate.csv"
      },
      "attributes": [
        { "name": "Datekey", "dataType": "date" },
        { "name": "FullDateLabel", "dataType": "date" },
        { "name": "DateDescription", "dataType": "date" },
        { "name": "CalendarYear", "dataType": "int64" },
        { "name": "CalendarYearLabel", "dataType": "string" },
        { "name": "CalendarHalfYear", "dataType": "int64" },
        { "name": "CalendarHalfYearLabel", "dataType": "string" },
        { "name": "CalendarQuarter", "dataType": "int64" },
        { "name": "CalendarQuarterLabel", "dataType": "string" },
        { "name": "CalendarMonth", "dataType": "int64" },
        { "name": "CalendarMonthLabel", "dataType": "string" },
        { "name": "CalendarWeek", "dataType": "int64" },
        { "name": "CalendarWeekLabel", "dataType": "string" },
        { "name": "CalendarDayOfWeek", "dataType": "int64" },
        { "name": "CalendarDayOfWeekLabel", "dataType": "string" },
        { "name": "FiscalYear", "dataType": "int64" },
        { "name": "FiscalYearLabel", "dataType": "string" },
        { "name": "FiscalHalfYear", "dataType": "int64" },
        { "name": "FiscalHalfYearLabel", "dataType": "string" },
        { "name": "FiscalQuarter", "dataType": "int64" },
        { "name": "FiscalQuarterLabel", "dataType": "string" },
        { "name": "FiscalMonth", "dataType": "int64" },
        { "name": "FiscalMonthLabel", "dataType": "string" },
        { "name": "IsWorkDay", "dataType": "string" },
        { "name": "IsHoliday", "dataType": "int64" },
        { "name": "HolidayName", "dataType": "string" },
        { "name": "EuropeSeason", "dataType": "string" },
        { "name": "NorthAmericaSeason", "dataType": "string" },
        { "name": "AsiaSeason", "dataType": "string" }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "DimEmployee",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimEmployee.csv"
      },
      "attributes": [
        { "name": "EmployeeKey", "dataType": "int64" },
        { "name": "ParentEmployeeKey", "dataType": "int64" },
        { "name": "FirstName", "dataType": "string" },
        { "name": "LastName", "dataType": "string" },
        { "name": "MiddleName", "dataType": "string" },
        { "name": "Title", "dataType": "string" },
        { "name": "HireDate", "dataType": "date" },
        { "name": "BirthDate", "dataType": "date" },
        { "name": "EmailAddress", "dataType": "string" },
        { "name": "Phone", "dataType": "string" },
        { "name": "MaritalStatus", "dataType": "string" },
        { "name": "EmergencyContactName", "dataType": "string" },
        { "name": "EmergencyContactPhone", "dataType": "string" },
        { "name": "SalariedFlag", "dataType": "int64" },
        { "name": "Gender", "dataType": "string" },
        { "name": "PayFrequency", "dataType": "int64" },
        { "name": "BaseRate", "dataType": "double" },
        { "name": "VacationHours", "dataType": "int64" },
        { "name": "CurrentFlag", "dataType": "int64" },
        { "name": "SalesPersonFlag", "dataType": "int64" },
        { "name": "DepartmentName", "dataType": "string" },
        { "name": "StartDate", "dataType": "date" },
        { "name": "EndDate", "dataType": "date" },
        { "name": "Status", "dataType": "string" },
        { "name": "ETLLoadID", "dataType": "int64" },
        { "name": "LoadDate", "dataType": "dateTime" },
        { "name": "UpdateDate", "dataType": "dateTime" }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "DimStore",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimStore.csv"
      },
      "attributes": [
        { "name": "StoreKey", "dataType": "int64" },
        { "name": "GeographyKey", "dataType": "int64" },
        { "name": "StoreManager", "dataType": "int64" },
        { "name": "StoreType", "dataType": "string" },
        { "name": "StoreName", "dataType": "string" },
        { "name": "StoreDescription", "dataType": "string" },
        { "name": "Status", "dataType": "string" },
        { "name": "OpenDate", "dataType": "dateTime" },
        { "name": "CloseDate", "dataType": "dateTime" },
        { "name": "EntityKey", "dataType": "int64" },
        { "name": "ZipCode", "dataType": "int64" },
        { "name": "ZipCodeExtension", "dataType": "int64" },
        { "name": "StorePhone", "dataType": "string" },
        { "name": "StoreFax", "dataType": "string" },
        { "name": "AddressLine1", "dataType": "string" },
        { "name": "AddressLine2", "dataType": "string" },
        { "name": "CloseReason", "dataType": "string" },
        { "name": "EmployeeCount", "dataType": "int64" },
        { "name": "SellingAreaSize", "dataType": "int64" },
        { "name": "LastRemodelDate", "dataType": "dateTime" },
        { "name": "GeoLocation", "dataType": "string" },
        { "name": "Geometry", "dataType": "string" },
        { "name": "ETLLoadID", "dataType": "int64" },
        { "name": "LoadDate", "dataType": "dateTime" },
        { "name": "UpdateDate", "dataType": "dateTime" }
      ]
    }
  ]
}
