{
  "name": "Dataflow demo (final)",
  "description": "Demo of a dataflow for Day after Dashboard in a Day event.",
  "version": "1.0",
  "culture": "en-US",
  "modifiedTime": "2022-08-12T15:19:13.1120192+00:00",
  "ppdf:outputFileFormat": "Csv",
  "pbi:mashup": {
    "fastCombine": false,
    "allowNativeQueries": false,
    "queriesMetadata": {
      "DimProduct_raw": {
        "queryId": "b2a9c1da-3f2f-49c8-8d59-622dee438105",
        "queryName": "DimProduct_raw",
        "queryGroupId": "3d0c4337-eee9-4b93-8412-945ef435e1d5",
        "loadEnabled": true
      },
      "DimProductCategory_raw": {
        "queryId": "415d50a7-90b2-45f7-acfb-195f3782dcd8",
        "queryName": "DimProductCategory_raw",
        "queryGroupId": "3d0c4337-eee9-4b93-8412-945ef435e1d5",
        "loadEnabled": true
      },
      "DimProductSubcategory_raw": {
        "queryId": "a3c281f5-6af9-47fa-913d-77694e2d098c",
        "queryName": "DimProductSubcategory_raw",
        "queryGroupId": "3d0c4337-eee9-4b93-8412-945ef435e1d5",
        "loadEnabled": true
      },
      "DimCustomer_raw": {
        "queryId": "b8782f36-de41-4e0e-9c85-853fbfca4252",
        "queryName": "DimCustomer_raw",
        "queryGroupId": "3d0c4337-eee9-4b93-8412-945ef435e1d5",
        "loadEnabled": true
      },
      "DimGeography_raw": {
        "queryId": "cc87ce39-7471-4ffa-abc8-6c5e4ef0e8f7",
        "queryName": "DimGeography_raw",
        "queryGroupId": "3d0c4337-eee9-4b93-8412-945ef435e1d5",
        "loadEnabled": true
      },
      "FactOnlineSales_raw": {
        "queryId": "2ab36fa3-91a6-46bb-9bd6-81edf1a22efb",
        "queryName": "FactOnlineSales_raw",
        "queryGroupId": "3d0c4337-eee9-4b93-8412-945ef435e1d5",
        "loadEnabled": true
      },
      "FactOnlineSales": {
        "queryId": "b65edf16-9f9d-4a83-bbb9-2266833a50df",
        "queryName": "FactOnlineSales",
        "queryGroupId": "c3913e67-0737-4d8f-bfdc-5777691b1474",
        "loadEnabled": true
      },
      "DimDate": {
        "queryId": "37f72102-aa25-4005-b517-080c52baecd0",
        "queryName": "DimDate",
        "queryGroupId": "5343e771-fe55-4f6d-909a-35fe3c881564",
        "loadEnabled": true
      },
      "DimEmployee": {
        "queryId": "c2a07242-3c8f-4c3d-bb24-f3934eb7f4f1",
        "queryName": "DimEmployee",
        "queryGroupId": "5343e771-fe55-4f6d-909a-35fe3c881564",
        "loadEnabled": true
      },
      "fxGetFile": {
        "queryId": "620769f7-b1ac-4a7c-8998-1d0d38736fe1",
        "queryName": "fxGetFile"
      },
      "fxCreateKey": {
        "queryId": "a0203672-4b21-42b0-8746-0d6bcf495812",
        "queryName": "fxCreateKey"
      },
      "DimCustomer": {
        "queryId": "94bc3ec2-7cea-4318-962a-f7eaf57d90cd",
        "queryName": "DimCustomer",
        "queryGroupId": "c3913e67-0737-4d8f-bfdc-5777691b1474",
        "loadEnabled": true
      },
      "DimProduct": {
        "queryId": "70eb6d5e-666e-4c46-89c3-a179a082ff94",
        "queryName": "DimProduct",
        "queryGroupId": "c3913e67-0737-4d8f-bfdc-5777691b1474",
        "loadEnabled": true
      },
      "DimSalesTerritory": {
        "queryId": "038b0971-d74b-4bf8-8b19-8e6ee15b0adb",
        "queryName": "DimSalesTerritory",
        "queryGroupId": "5343e771-fe55-4f6d-909a-35fe3c881564",
        "loadEnabled": true
      },
      "DimStore": {
        "queryId": "151bdf07-8451-40f7-bd85-0298a48e05b1",
        "queryName": "DimStore",
        "queryGroupId": "5343e771-fe55-4f6d-909a-35fe3c881564",
        "loadEnabled": true
      }
    },
    "document": "section Section1;\r\nshared DimProduct_raw = let\n    Source = fxGetFile(\"DimProduct.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(Source, {{\"AvailableForSaleDate\", type datetime}, {\"ProductKey\", Int64.Type}, {\"ProductLabel\", Int64.Type}, {\"ProductName\", type text}, {\"ProductDescription\", type text}, {\"ProductSubcategoryKey\", Int64.Type}, {\"Manufacturer\", type text}, {\"BrandName\", type text}, {\"ClassID\", Int64.Type}, {\"ClassName\", type text}, {\"StyleID\", Int64.Type}, {\"StyleName\", type text}, {\"ColorID\", Int64.Type}, {\"ColorName\", type text}, {\"Size\", type text}, {\"SizeRange\", type text}, {\"SizeUnitMeasureID\", type text}, {\"Weight\", type number}, {\"WeightUnitMeasureID\", type text}, {\"UnitOfMeasureID\", Int64.Type}, {\"UnitOfMeasureName\", type text}, {\"StockTypeID\", Int64.Type}, {\"StockTypeName\", type text}, {\"UnitCost\", type number}, {\"UnitPrice\", type number}, {\"StopSaleDate\", type text}, {\"Status\", type text}, {\"ImageURL\", type text}, {\"ProductURL\", type text}})\nin\n    #\"Changed column type\";\r\nshared DimProductCategory_raw = let\n    Source = fxGetFile(\"DimProductCategory.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"ProductCategoryKey\",\n                    Int64.Type\n                },\n                {\n                    \"ProductCategoryLabel\",\n                    Int64.Type\n                },\n                {\n                    \"ProductCategoryName\",\n                    type text\n                },\n                {\n                    \"ProductCategoryDescription\",\n                    type text\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimProductSubcategory_raw = let\n    Source = fxGetFile(\"DimProductSubcategory.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"ProductSubcategoryKey\",\n                    Int64.Type\n                },\n                {\n                    \"ProductSubcategoryLabel\",\n                    Int64.Type\n                },\n                {\n                    \"ProductSubcategoryName\",\n                    type text\n                },\n                {\n                    \"ProductSubcategoryDescription\",\n                    type text\n                },\n                {\n                    \"ProductCategoryKey\",\n                    Int64.Type\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimCustomer_raw = let\n    Source = fxGetFile(\"DimCustomer.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"CustomerKey\",\n                    Int64.Type\n                },\n                {\n                    \"GeographyKey\",\n                    Int64.Type\n                },\n                {\n                    \"CustomerLabel\",\n                    type text\n                },\n                {\n                    \"FirstName\",\n                    type text\n                },\n                {\n                    \"MiddleName\",\n                    type text\n                },\n                {\n                    \"LastName\",\n                    type text\n                },\n                {\n                    \"NameStyle\",\n                    Int64.Type\n                },\n                {\n                    \"BirthDate\",\n                    type date\n                },\n                {\n                    \"MaritalStatus\",\n                    type text\n                },\n                {\n                    \"Suffix\",\n                    type text\n                },\n                {\n                    \"Title\",\n                    type text\n                },\n                {\n                    \"EmailAddress\",\n                    type text\n                },\n                {\n                    \"YearlyIncome\",\n                    Int64.Type\n                },\n                {\n                    \"TotalChildren\",\n                    Int64.Type\n                },\n                {\n                    \"NumberChildrenAtHome\",\n                    Int64.Type\n                },\n                {\n                    \"Education\",\n                    type text\n                },\n                {\n                    \"Occupation\",\n                    type text\n                },\n                {\n                    \"HouseOwnerFlag\",\n                    Int64.Type\n                },\n                {\n                    \"NumberCarsOwned\",\n                    Int64.Type\n                },\n                {\n                    \"AddressLine1\",\n                    type text\n                },\n                {\n                    \"AddressLine2\",\n                    type text\n                },\n                {\n                    \"Phone\",\n                    type text\n                },\n                {\n                    \"DateFirstPurchase\",\n                    type date\n                },\n                {\n                    \"CustomerType\",\n                    type text\n                },\n                {\n                    \"CompanyName\",\n                    type text\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimGeography_raw = let\n    Source = fxGetFile(\"DimGeography.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"GeographyKey\",\n                    Int64.Type\n                },\n                {\n                    \"GeographyType\",\n                    type text\n                },\n                {\n                    \"ContinentName\",\n                    type text\n                },\n                {\n                    \"CityName\",\n                    type text\n                },\n                {\n                    \"StateProvinceName\",\n                    type text\n                },\n                {\n                    \"RegionCountryName\",\n                    type text\n                },\n                {\n                    \"Geometry\",\n                    type text\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared FactOnlineSales_raw = let\n    fileNameUpdate =\n        (#\"File number\" as number) as text =>\n            let\n                Source =\n                    Text.Combine(\n                        {\n                            \"FactOnlineSales_\",\n                            Text.From(#\"File number\"),\n                            \".parquet\"\n                        }\n                    )\n            in\n                Source,\n    tableReturn = [\n        fileCount = 1,\n        fileName = fileNameUpdate(fileCount),\n        data = fxGetFile(fileName)\n    ],\n    Source =\n        List.Generate(\n            () => tableReturn,\n            each try not Table.IsEmpty([data]) otherwise false,\n            each\n                [\n                    fileCount = [fileCount] + 1,\n                    fileName = fileNameUpdate(fileCount),\n                    data =\n                        try fxGetFile(fileName)\n                        otherwise\n                            #table(\n                                {},\n                                {}\n                            )\n                ]\n        ),\n    #\"Converted to table\" =\n        Table.FromList(\n            Source,\n            Splitter.SplitByNothing(),\n            null,\n            null,\n            ExtraValues.Error\n        ),\n    #\"Expanded Column1\" =\n        Table.ExpandRecordColumn(\n            #\"Converted to table\",\n            \"Column1\",\n            {\"data\"},\n            {\"data\"}\n        ),\r\n  #\"Expanded data\" = Table.ExpandTableColumn(#\"Expanded Column1\", \"data\", {\"OnlineSalesKey\", \"DateKey\", \"StoreKey\", \"ProductKey\", \"CustomerKey\", \"SalesQuantity\", \"SalesAmount\", \"ReturnQuantity\", \"ReturnAmount\", \"DiscountQuantity\", \"DiscountAmount\"}, {\"OnlineSalesKey\", \"DateKey\", \"StoreKey\", \"ProductKey\", \"CustomerKey\", \"SalesQuantity\", \"SalesAmount\", \"ReturnQuantity\", \"ReturnAmount\", \"DiscountQuantity\", \"DiscountAmount\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded data\", {{\"OnlineSalesKey\", Int64.Type}, {\"DateKey\", type datetime}, {\"StoreKey\", Int64.Type}, {\"ProductKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"SalesQuantity\", Int64.Type}, {\"SalesAmount\", type number}, {\"ReturnQuantity\", Int64.Type}, {\"ReturnAmount\", Int64.Type}, {\"DiscountQuantity\", Int64.Type}, {\"DiscountAmount\", type number}})\nin\n    #\"Changed column type\";\r\nshared FactOnlineSales = let\r\n  Source = FactOnlineSales_raw\r\nin\r\n  Source;\r\nshared DimDate = let\n    Source = fxGetFile(\"DimDate.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"Datekey\",\n                    type datetime\n                },\n                {\n                    \"FullDateLabel\",\n                    type date\n                },\n                {\n                    \"DateDescription\",\n                    type date\n                },\n                {\n                    \"CalendarYear\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarYearLabel\",\n                    type text\n                },\n                {\n                    \"CalendarHalfYear\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarHalfYearLabel\",\n                    type text\n                },\n                {\n                    \"CalendarQuarter\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarQuarterLabel\",\n                    type text\n                },\n                {\n                    \"CalendarMonth\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarMonthLabel\",\n                    type text\n                },\n                {\n                    \"CalendarWeek\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarWeekLabel\",\n                    type text\n                },\n                {\n                    \"CalendarDayOfWeek\",\n                    Int64.Type\n                },\n                {\n                    \"CalendarDayOfWeekLabel\",\n                    type text\n                },\n                {\n                    \"FiscalYear\",\n                    Int64.Type\n                },\n                {\n                    \"FiscalYearLabel\",\n                    type text\n                },\n                {\n                    \"FiscalHalfYear\",\n                    Int64.Type\n                },\n                {\n                    \"FiscalHalfYearLabel\",\n                    type text\n                },\n                {\n                    \"FiscalQuarter\",\n                    Int64.Type\n                },\n                {\n                    \"FiscalQuarterLabel\",\n                    type text\n                },\n                {\n                    \"FiscalMonth\",\n                    Int64.Type\n                },\n                {\n                    \"FiscalMonthLabel\",\n                    type text\n                },\n                {\n                    \"IsWorkDay\",\n                    type text\n                },\n                {\n                    \"IsHoliday\",\n                    Int64.Type\n                },\n                {\n                    \"HolidayName\",\n                    type text\n                },\n                {\n                    \"EuropeSeason\",\n                    type text\n                },\n                {\n                    \"NorthAmericaSeason\",\n                    type text\n                },\n                {\n                    \"AsiaSeason\",\n                    type text\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimEmployee = let\n    Source = fxGetFile(\"DimEmployee.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"EmployeeKey\",\n                    Int64.Type\n                },\n                {\n                    \"ParentEmployeeKey\",\n                    Int64.Type\n                },\n                {\n                    \"FirstName\",\n                    type text\n                },\n                {\n                    \"LastName\",\n                    type text\n                },\n                {\n                    \"MiddleName\",\n                    type text\n                },\n                {\n                    \"Title\",\n                    type text\n                },\n                {\n                    \"HireDate\",\n                    type date\n                },\n                {\n                    \"BirthDate\",\n                    type date\n                },\n                {\n                    \"EmailAddress\",\n                    type text\n                },\n                {\n                    \"Phone\",\n                    type text\n                },\n                {\n                    \"MaritalStatus\",\n                    type text\n                },\n                {\n                    \"EmergencyContactName\",\n                    type text\n                },\n                {\n                    \"EmergencyContactPhone\",\n                    type text\n                },\n                {\n                    \"SalariedFlag\",\n                    Int64.Type\n                },\n                {\n                    \"Gender\",\n                    type text\n                },\n                {\n                    \"PayFrequency\",\n                    Int64.Type\n                },\n                {\n                    \"BaseRate\",\n                    type number\n                },\n                {\n                    \"VacationHours\",\n                    Int64.Type\n                },\n                {\n                    \"CurrentFlag\",\n                    Int64.Type\n                },\n                {\n                    \"SalesPersonFlag\",\n                    Int64.Type\n                },\n                {\n                    \"DepartmentName\",\n                    type text\n                },\n                {\n                    \"StartDate\",\n                    type date\n                },\n                {\n                    \"EndDate\",\n                    type date\n                },\n                {\n                    \"Status\",\n                    type text\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared fxGetFile = let\n    fxGetFile =\n        (#\"File Name\" as text) =>\n            let\n                webAddress = \"https://raw.githubusercontent.com/microsoft/pbiworkshops/main/Day%20After%20Dashboard%20in%20a%20Day/Source_Files\",\n                Source =\n                    if\n                        Text.AfterDelimiter(#\"File Name\", \".\")\n                        = \"csv\"\n                    then\n                        Table.PromoteHeaders(\n                            Csv.Document(\n                                Web.Contents(\n                                    webAddress,\n                                    [\n                                        RelativePath = #\"File Name\",\n                                        ManualStatusHandling = {\n                                            404\n                                        }\n                                    ]\n                                ),\n                                [\n                                    Delimiter = \"|\",\n                                    Encoding = 65001,\n                                    QuoteStyle = QuoteStyle.None\n                                ]\n                            )\n                        )\n                    else\n                        Parquet.Document(\n                            Binary.Buffer(\n                                Web.Contents(\n                                    webAddress,\n                                    [\n                                        RelativePath = #\"File Name\",\n                                        ManualStatusHandling = {\n                                            404\n                                        }\n                                    ]\n                                )\n                            ),\n                            [\n                                Compression = Compression.Snappy,\n                                LegacyColumnNameEncoding = false,\n                                MaxDepth = null\n                            ]\n                        )\n            in\n                Source,\n    Documentation_Meta = [\n        Documentation.Name = \"Day After Dashboard in a Day - Sample data\",\n        Documentation.Description = \"Obtains the pipe delimited csv files from the GitHub repository for Day After Dashboard in a Day. Short link: https://aka.ms/pbiworkshops\"\n    ],\n    #\"Add Documentation\" =\n        Value.ReplaceType(\n            fxGetFile,\n            Value.ReplaceMetadata(\n                Value.Type(fxGetFile),\n                Documentation_Meta\n            )\n        )\nin\n    #\"Add Documentation\";\r\nshared fxCreateKey = let\r\n  CreateKey = (#\"Date time value\" as datetime) as number =>\n            let\n                Source =\n                    DateTime.ToText(\n                        #\"Date time value\",\n                        \"yyyyMMdd\"\n                    ),\n                #\"Convert to number\" = Number.From(Source)\n            in\n                #\"Convert to number\",\r\n  Documentation = [\n        Documentation.Name = \"Create an integer surrogate key\",\n        Documentation.Description = \"Converts a datetime value to an integer in the format of yyyyMMdd.\"\n    ],\r\n  Output = Value.ReplaceType(CreateKey, Value.ReplaceMetadata(Value.Type(CreateKey), Documentation))\r\nin\r\n  Output;\r\nshared DimCustomer = let\n    Source =\n        Table.NestedJoin(\n            DimCustomer_raw,\n            {\"GeographyKey\"},\n            DimGeography_raw,\n            {\"GeographyKey\"},\n            \"DimGeography_raw\",\n            JoinKind.Inner\n        ),\n    #\"Expanded DimGeography_raw\" =\n        Table.ExpandTableColumn(\n            Source,\n            \"DimGeography_raw\",\n            {\n                \"City\",\n                \"StateProvinceCode\",\n                \"StateProvinceName\",\n                \"CountryRegionCode\",\n                \"EnglishCountryRegionName\",\n                \"SpanishCountryRegionName\",\n                \"FrenchCountryRegionName\",\n                \"PostalCode\",\n                \"SalesTerritoryKey\",\n                \"IpAddressLocator\"\n            },\n            {\n                \"City\",\n                \"StateProvinceCode\",\n                \"StateProvinceName\",\n                \"CountryRegionCode\",\n                \"EnglishCountryRegionName\",\n                \"SpanishCountryRegionName\",\n                \"FrenchCountryRegionName\",\n                \"PostalCode\",\n                \"SalesTerritoryKey\",\n                \"IpAddressLocator\"\n            }\n        ),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            #\"Expanded DimGeography_raw\",\n            {\n                {\n                    \"CustomerKey\",\n                    Int64.Type\n                },\n                {\n                    \"GeographyKey\",\n                    Int64.Type\n                },\n                {\n                    \"CustomerLabel\",\n                    type text\n                },\n                {\n                    \"Title\",\n                    type text\n                },\n                {\n                    \"FirstName\",\n                    type text\n                },\n                {\n                    \"MiddleName\",\n                    type text\n                },\n                {\n                    \"LastName\",\n                    type text\n                },\n                {\n                    \"NameStyle\",\n                    Int64.Type\n                },\n                {\n                    \"BirthDate\",\n                    type date\n                },\n                {\n                    \"MaritalStatus\",\n                    type text\n                },\n                {\n                    \"Suffix\",\n                    type text\n                },\n                {\n                    \"EmailAddress\",\n                    type text\n                },\n                {\n                    \"YearlyIncome\",\n                    Int64.Type\n                },\n                {\n                    \"TotalChildren\",\n                    Int64.Type\n                },\n                {\n                    \"NumberChildrenAtHome\",\n                    Int64.Type\n                },\n                {\n                    \"Education\",\n                    type text\n                },\n                {\n                    \"Occupation\",\n                    type text\n                },\n                {\n                    \"HouseOwnerFlag\",\n                    Int64.Type\n                },\n                {\n                    \"NumberCarsOwned\",\n                    Int64.Type\n                },\n                {\n                    \"AddressLine1\",\n                    type text\n                },\n                {\n                    \"AddressLine2\",\n                    type text\n                },\n                {\n                    \"Phone\",\n                    type text\n                },\n                {\n                    \"DateFirstPurchase\",\n                    type date\n                },\n                {\n                    \"CustomerType\",\n                    type text\n                },\n                {\n                    \"CompanyName\",\n                    type text\n                },\n                {\n                    \"StateProvinceCode\",\n                    type text\n                },\n                {\n                    \"CountryRegionCode\",\n                    type text\n                },\n                {\n                    \"EnglishCountryRegionName\",\n                    type text\n                },\n                {\n                    \"SpanishCountryRegionName\",\n                    type text\n                },\n                {\n                    \"FrenchCountryRegionName\",\n                    type text\n                },\n                {\n                    \"PostalCode\",\n                    type text\n                },\n                {\n                    \"SalesTerritoryKey\",\n                    type text\n                },\n                {\n                    \"IpAddressLocator\",\n                    type text\n                },\n                {\n                    \"City\",\n                    type text\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\nshared DimProduct = let\r\n  Source = Table.NestedJoin(DimProduct_raw, {\"ProductSubcategoryKey\"}, DimProductSubcategory_raw, {\"ProductSubcategoryKey\"}, \"DimProductSubcategory_raw\", JoinKind.LeftOuter),\r\n  #\"Expanded DimProductSubcategory_raw\" = Table.ExpandTableColumn(Source, \"DimProductSubcategory_raw\", {\"ProductSubcategoryAlternateKey\", \"EnglishProductSubcategoryName\", \"SpanishProductSubcategoryName\", \"FrenchProductSubcategoryName\", \"ProductCategoryKey\"}, {\"ProductSubcategoryAlternateKey\", \"EnglishProductSubcategoryName\", \"SpanishProductSubcategoryName\", \"FrenchProductSubcategoryName\", \"ProductCategoryKey\"}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Expanded DimProductSubcategory_raw\", {\"ProductCategoryKey\"}, DimProductCategory_raw, {\"ProductCategoryKey\"}, \"DimProductCategory_raw\", JoinKind.LeftOuter),\r\n  #\"Remove columns\" = Table.RemoveColumns(#\"Merged queries\", Table.ColumnsOfType(#\"Merged queries\", {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\nshared DimSalesTerritory = let\r\n  Source = fxGetFile(\"DimSalesTerritory.csv\")\r\nin\r\n  Source;\r\nshared DimStore = let\n    Source = fxGetFile(\"DimStore.csv\"),\n    #\"Changed column type\" =\n        Table.TransformColumnTypes(\n            Source,\n            {\n                {\n                    \"StoreKey\",\n                    Int64.Type\n                },\n                {\n                    \"GeographyKey\",\n                    Int64.Type\n                },\n                {\n                    \"StoreManager\",\n                    Int64.Type\n                },\n                {\n                    \"StoreType\",\n                    type text\n                },\n                {\n                    \"StoreName\",\n                    type text\n                },\n                {\n                    \"StoreDescription\",\n                    type text\n                },\n                {\n                    \"Status\",\n                    type text\n                },\n                {\n                    \"OpenDate\",\n                    type datetime\n                },\n                {\n                    \"CloseDate\",\n                    type datetime\n                },\n                {\n                    \"EntityKey\",\n                    Int64.Type\n                },\n                {\n                    \"ZipCode\",\n                    Int64.Type\n                },\n                {\n                    \"ZipCodeExtension\",\n                    Int64.Type\n                },\n                {\n                    \"StorePhone\",\n                    type text\n                },\n                {\n                    \"StoreFax\",\n                    type text\n                },\n                {\n                    \"AddressLine1\",\n                    type text\n                },\n                {\n                    \"AddressLine2\",\n                    type text\n                },\n                {\n                    \"CloseReason\",\n                    type text\n                },\n                {\n                    \"EmployeeCount\",\n                    Int64.Type\n                },\n                {\n                    \"SellingAreaSize\",\n                    Int64.Type\n                },\n                {\n                    \"LastRemodelDate\",\n                    type datetime\n                },\n                {\n                    \"GeoLocation\",\n                    type text\n                },\n                {\n                    \"Geometry\",\n                    type text\n                }\n            }\n        )\nin\n    #\"Changed column type\";\r\n",
    "connectionOverrides": [
      {
        "path": "https://raw.githubusercontent.com/microsoft/pbiworkshops/main/Day%20After%20Dashboard%20in%20a%20Day/Source_Files",
        "kind": "Web",
        "provider": "CdsA",
        "authenticationKind": null,
        "environmentName": null,
        "apiName": null,
        "connectionName": "57a64d1c-0ad0-443d-bba4-40b7887c9283",
        "audience": null
      }
    ]
  },
  "annotations": [
    {
      "name": "pbi:QueryGroups",
      "value": "[{\"id\":\"3d0c4337-eee9-4b93-8412-945ef435e1d5\",\"name\":\"Data staging\",\"description\":\"Data that will be ingested from the source and referenced in computed tables for transformations via the enhanced compute engine.\",\"parentId\":null,\"order\":0},{\"id\":\"5343e771-fe55-4f6d-909a-35fe3c881564\",\"name\":\"Data load\",\"description\":\"Data that will be ingested from the source without transformations.\",\"parentId\":null,\"order\":1},{\"id\":\"c3913e67-0737-4d8f-bfdc-5777691b1474\",\"name\":\"Data transformation\",\"description\":\"Data that will be ingested from the data lake storage for transformations.\",\"parentId\":null,\"order\":2}]"
    }
  ],
  "entities": [
    {
      "$type": "LocalEntity",
      "name": "DimProduct_raw",
      "description": "Description when connecting.",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimProduct_raw.csv"
      },
      "attributes": [
        { "name": "ProductKey", "dataType": "int64" },
        { "name": "ProductLabel", "dataType": "int64" },
        { "name": "ProductName", "dataType": "string" },
        { "name": "ProductDescription", "dataType": "string" },
        { "name": "ProductSubcategoryKey", "dataType": "int64" },
        { "name": "Manufacturer", "dataType": "string" },
        { "name": "BrandName", "dataType": "string" },
        { "name": "ClassID", "dataType": "int64" },
        { "name": "ClassName", "dataType": "string" },
        { "name": "StyleID", "dataType": "int64" },
        { "name": "StyleName", "dataType": "string" },
        { "name": "ColorID", "dataType": "int64" },
        { "name": "ColorName", "dataType": "string" },
        { "name": "Size", "dataType": "string" },
        { "name": "SizeRange", "dataType": "string" },
        { "name": "SizeUnitMeasureID", "dataType": "string" },
        { "name": "Weight", "dataType": "double" },
        { "name": "WeightUnitMeasureID", "dataType": "string" },
        { "name": "UnitOfMeasureID", "dataType": "int64" },
        { "name": "UnitOfMeasureName", "dataType": "string" },
        { "name": "StockTypeID", "dataType": "int64" },
        { "name": "StockTypeName", "dataType": "string" },
        { "name": "UnitCost", "dataType": "double" },
        { "name": "UnitPrice", "dataType": "double" },
        { "name": "AvailableForSaleDate", "dataType": "dateTime" },
        { "name": "StopSaleDate", "dataType": "string" },
        { "name": "Status", "dataType": "string" },
        { "name": "ImageURL", "dataType": "string" },
        { "name": "ProductURL", "dataType": "string" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "DimProductCategory_raw",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimProductCategory_raw.csv"
      },
      "attributes": [
        { "name": "ProductCategoryKey", "dataType": "int64" },
        { "name": "ProductCategoryLabel", "dataType": "int64" },
        { "name": "ProductCategoryName", "dataType": "string" },
        { "name": "ProductCategoryDescription", "dataType": "string" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "DimProductSubcategory_raw",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimProductSubcategory_raw.csv"
      },
      "attributes": [
        { "name": "ProductSubcategoryKey", "dataType": "int64" },
        { "name": "ProductSubcategoryLabel", "dataType": "int64" },
        { "name": "ProductSubcategoryName", "dataType": "string" },
        { "name": "ProductSubcategoryDescription", "dataType": "string" },
        { "name": "ProductCategoryKey", "dataType": "int64" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "DimCustomer_raw",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimCustomer_raw.csv"
      },
      "attributes": [
        { "name": "CustomerKey", "dataType": "int64" },
        { "name": "GeographyKey", "dataType": "int64" },
        { "name": "CustomerLabel", "dataType": "string" },
        { "name": "FirstName", "dataType": "string" },
        { "name": "MiddleName", "dataType": "string" },
        { "name": "LastName", "dataType": "string" },
        { "name": "NameStyle", "dataType": "int64" },
        { "name": "BirthDate", "dataType": "date" },
        { "name": "MaritalStatus", "dataType": "string" },
        { "name": "Suffix", "dataType": "string" },
        { "name": "Title", "dataType": "string" },
        { "name": "EmailAddress", "dataType": "string" },
        { "name": "YearlyIncome", "dataType": "int64" },
        { "name": "TotalChildren", "dataType": "int64" },
        { "name": "NumberChildrenAtHome", "dataType": "int64" },
        { "name": "Education", "dataType": "string" },
        { "name": "Occupation", "dataType": "string" },
        { "name": "HouseOwnerFlag", "dataType": "int64" },
        { "name": "NumberCarsOwned", "dataType": "int64" },
        { "name": "AddressLine1", "dataType": "string" },
        { "name": "AddressLine2", "dataType": "string" },
        { "name": "Phone", "dataType": "string" },
        { "name": "DateFirstPurchase", "dataType": "date" },
        { "name": "CustomerType", "dataType": "string" },
        { "name": "CompanyName", "dataType": "string" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "DimGeography_raw",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimGeography_raw.csv"
      },
      "attributes": [
        { "name": "GeographyKey", "dataType": "int64" },
        { "name": "GeographyType", "dataType": "string" },
        { "name": "ContinentName", "dataType": "string" },
        { "name": "CityName", "dataType": "string" },
        { "name": "StateProvinceName", "dataType": "string" },
        { "name": "RegionCountryName", "dataType": "string" },
        { "name": "Geometry", "dataType": "string" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "FactOnlineSales_raw",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "FactOnlineSales_raw.csv"
      },
      "attributes": [
        { "name": "OnlineSalesKey", "dataType": "int64" },
        { "name": "DateKey", "dataType": "dateTime" },
        { "name": "StoreKey", "dataType": "int64" },
        { "name": "ProductKey", "dataType": "int64" },
        { "name": "CustomerKey", "dataType": "int64" },
        { "name": "SalesQuantity", "dataType": "int64" },
        { "name": "SalesAmount", "dataType": "double" },
        { "name": "ReturnQuantity", "dataType": "int64" },
        { "name": "ReturnAmount", "dataType": "int64" },
        { "name": "DiscountQuantity", "dataType": "int64" },
        { "name": "DiscountAmount", "dataType": "double" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "FactOnlineSales",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "FactOnlineSales.csv"
      },
      "annotations": [
        { "name": "pbi:EntityTypeDisplayHint", "value": "CalculatedEntity" }
      ],
      "attributes": [
        { "name": "OnlineSalesKey", "dataType": "int64" },
        { "name": "DateKey", "dataType": "dateTime" },
        { "name": "StoreKey", "dataType": "int64" },
        { "name": "ProductKey", "dataType": "int64" },
        { "name": "CustomerKey", "dataType": "int64" },
        { "name": "SalesQuantity", "dataType": "int64" },
        { "name": "SalesAmount", "dataType": "double" },
        { "name": "ReturnQuantity", "dataType": "int64" },
        { "name": "ReturnAmount", "dataType": "int64" },
        { "name": "DiscountQuantity", "dataType": "int64" },
        { "name": "DiscountAmount", "dataType": "double" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "DimDate",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimDate.csv"
      },
      "attributes": [
        { "name": "Datekey", "dataType": "dateTime" },
        { "name": "FullDateLabel", "dataType": "date" },
        { "name": "DateDescription", "dataType": "date" },
        { "name": "CalendarYear", "dataType": "int64" },
        { "name": "CalendarYearLabel", "dataType": "string" },
        { "name": "CalendarHalfYear", "dataType": "int64" },
        { "name": "CalendarHalfYearLabel", "dataType": "string" },
        { "name": "CalendarQuarter", "dataType": "int64" },
        { "name": "CalendarQuarterLabel", "dataType": "string" },
        { "name": "CalendarMonth", "dataType": "int64" },
        { "name": "CalendarMonthLabel", "dataType": "string" },
        { "name": "CalendarWeek", "dataType": "int64" },
        { "name": "CalendarWeekLabel", "dataType": "string" },
        { "name": "CalendarDayOfWeek", "dataType": "int64" },
        { "name": "CalendarDayOfWeekLabel", "dataType": "string" },
        { "name": "FiscalYear", "dataType": "int64" },
        { "name": "FiscalYearLabel", "dataType": "string" },
        { "name": "FiscalHalfYear", "dataType": "int64" },
        { "name": "FiscalHalfYearLabel", "dataType": "string" },
        { "name": "FiscalQuarter", "dataType": "int64" },
        { "name": "FiscalQuarterLabel", "dataType": "string" },
        { "name": "FiscalMonth", "dataType": "int64" },
        { "name": "FiscalMonthLabel", "dataType": "string" },
        { "name": "IsWorkDay", "dataType": "string" },
        { "name": "IsHoliday", "dataType": "int64" },
        { "name": "HolidayName", "dataType": "string" },
        { "name": "EuropeSeason", "dataType": "string" },
        { "name": "NorthAmericaSeason", "dataType": "string" },
        { "name": "AsiaSeason", "dataType": "string" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "DimEmployee",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimEmployee.csv"
      },
      "attributes": [
        { "name": "EmployeeKey", "dataType": "int64" },
        { "name": "ParentEmployeeKey", "dataType": "int64" },
        { "name": "FirstName", "dataType": "string" },
        { "name": "LastName", "dataType": "string" },
        { "name": "MiddleName", "dataType": "string" },
        { "name": "Title", "dataType": "string" },
        { "name": "HireDate", "dataType": "date" },
        { "name": "BirthDate", "dataType": "date" },
        { "name": "EmailAddress", "dataType": "string" },
        { "name": "Phone", "dataType": "string" },
        { "name": "MaritalStatus", "dataType": "string" },
        { "name": "EmergencyContactName", "dataType": "string" },
        { "name": "EmergencyContactPhone", "dataType": "string" },
        { "name": "SalariedFlag", "dataType": "int64" },
        { "name": "Gender", "dataType": "string" },
        { "name": "PayFrequency", "dataType": "int64" },
        { "name": "BaseRate", "dataType": "double" },
        { "name": "VacationHours", "dataType": "int64" },
        { "name": "CurrentFlag", "dataType": "int64" },
        { "name": "SalesPersonFlag", "dataType": "int64" },
        { "name": "DepartmentName", "dataType": "string" },
        { "name": "StartDate", "dataType": "date" },
        { "name": "EndDate", "dataType": "date" },
        { "name": "Status", "dataType": "string" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "DimCustomer",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimCustomer.csv"
      },
      "annotations": [
        { "name": "pbi:EntityTypeDisplayHint", "value": "CalculatedEntity" }
      ],
      "attributes": [
        { "name": "CustomerKey", "dataType": "int64" },
        { "name": "GeographyKey", "dataType": "int64" },
        { "name": "CustomerLabel", "dataType": "string" },
        { "name": "FirstName", "dataType": "string" },
        { "name": "MiddleName", "dataType": "string" },
        { "name": "LastName", "dataType": "string" },
        { "name": "NameStyle", "dataType": "int64" },
        { "name": "BirthDate", "dataType": "date" },
        { "name": "MaritalStatus", "dataType": "string" },
        { "name": "Suffix", "dataType": "string" },
        { "name": "Title", "dataType": "string" },
        { "name": "EmailAddress", "dataType": "string" },
        { "name": "YearlyIncome", "dataType": "int64" },
        { "name": "TotalChildren", "dataType": "int64" },
        { "name": "NumberChildrenAtHome", "dataType": "int64" },
        { "name": "Education", "dataType": "string" },
        { "name": "Occupation", "dataType": "string" },
        { "name": "HouseOwnerFlag", "dataType": "int64" },
        { "name": "NumberCarsOwned", "dataType": "int64" },
        { "name": "AddressLine1", "dataType": "string" },
        { "name": "AddressLine2", "dataType": "string" },
        { "name": "Phone", "dataType": "string" },
        { "name": "DateFirstPurchase", "dataType": "date" },
        { "name": "CustomerType", "dataType": "string" },
        { "name": "CompanyName", "dataType": "string" },
        { "name": "City", "dataType": "string" },
        { "name": "StateProvinceCode", "dataType": "string" },
        { "name": "StateProvinceName", "dataType": "string" },
        { "name": "CountryRegionCode", "dataType": "string" },
        { "name": "EnglishCountryRegionName", "dataType": "string" },
        { "name": "SpanishCountryRegionName", "dataType": "string" },
        { "name": "FrenchCountryRegionName", "dataType": "string" },
        { "name": "PostalCode", "dataType": "string" },
        { "name": "SalesTerritoryKey", "dataType": "string" },
        { "name": "IpAddressLocator", "dataType": "string" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "DimProduct",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimProduct.csv"
      },
      "annotations": [
        { "name": "pbi:EntityTypeDisplayHint", "value": "CalculatedEntity" }
      ],
      "attributes": [
        { "name": "ProductKey", "dataType": "int64" },
        { "name": "ProductLabel", "dataType": "int64" },
        { "name": "ProductName", "dataType": "string" },
        { "name": "ProductDescription", "dataType": "string" },
        { "name": "ProductSubcategoryKey", "dataType": "int64" },
        { "name": "Manufacturer", "dataType": "string" },
        { "name": "BrandName", "dataType": "string" },
        { "name": "ClassID", "dataType": "int64" },
        { "name": "ClassName", "dataType": "string" },
        { "name": "StyleID", "dataType": "int64" },
        { "name": "StyleName", "dataType": "string" },
        { "name": "ColorID", "dataType": "int64" },
        { "name": "ColorName", "dataType": "string" },
        { "name": "Size", "dataType": "string" },
        { "name": "SizeRange", "dataType": "string" },
        { "name": "SizeUnitMeasureID", "dataType": "string" },
        { "name": "Weight", "dataType": "double" },
        { "name": "WeightUnitMeasureID", "dataType": "string" },
        { "name": "UnitOfMeasureID", "dataType": "int64" },
        { "name": "UnitOfMeasureName", "dataType": "string" },
        { "name": "StockTypeID", "dataType": "int64" },
        { "name": "StockTypeName", "dataType": "string" },
        { "name": "UnitCost", "dataType": "double" },
        { "name": "UnitPrice", "dataType": "double" },
        { "name": "AvailableForSaleDate", "dataType": "dateTime" },
        { "name": "StopSaleDate", "dataType": "string" },
        { "name": "Status", "dataType": "string" },
        { "name": "ImageURL", "dataType": "string" },
        { "name": "ProductURL", "dataType": "string" },
        { "name": "ProductCategoryKey", "dataType": "int64" }
      ],
      "partitions": []
    },
    {
      "$type": "LocalEntity",
      "name": "DimSalesTerritory",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimSalesTerritory.csv"
      },
      "attributes": [{ "name": "404: Not Found", "dataType": "string" }],
      "partitions": [
        {
          "name": "FullRefreshPolicyPartition",
          "refreshTime": "2022-08-12T15:19:42.4560892+00:00",
          "location": "https://dfmsitscuscdsa.blob.core.windows.net:443/df8a8b47-2704-471d-9e56-e83aeaeadc6d/DimSalesTerritory.csv?snapshot=2022-08-12T15%3A19%3A41.9991132Z"
        }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "DimStore",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "DimStore.csv"
      },
      "attributes": [
        { "name": "StoreKey", "dataType": "int64" },
        { "name": "GeographyKey", "dataType": "int64" },
        { "name": "StoreManager", "dataType": "int64" },
        { "name": "StoreType", "dataType": "string" },
        { "name": "StoreName", "dataType": "string" },
        { "name": "StoreDescription", "dataType": "string" },
        { "name": "Status", "dataType": "string" },
        { "name": "OpenDate", "dataType": "dateTime" },
        { "name": "CloseDate", "dataType": "dateTime" },
        { "name": "EntityKey", "dataType": "int64" },
        { "name": "ZipCode", "dataType": "int64" },
        { "name": "ZipCodeExtension", "dataType": "int64" },
        { "name": "StorePhone", "dataType": "string" },
        { "name": "StoreFax", "dataType": "string" },
        { "name": "AddressLine1", "dataType": "string" },
        { "name": "AddressLine2", "dataType": "string" },
        { "name": "CloseReason", "dataType": "string" },
        { "name": "EmployeeCount", "dataType": "int64" },
        { "name": "SellingAreaSize", "dataType": "int64" },
        { "name": "LastRemodelDate", "dataType": "dateTime" },
        { "name": "GeoLocation", "dataType": "string" },
        { "name": "Geometry", "dataType": "string" }
      ],
      "partitions": []
    }
  ]
}
